"""Portas (interfaces) que a application exige da infraestrutura.

As implementações concretas (SQLModel) vivem em infrastructure/repositories.py.
Tipagem das entidades via TYPE_CHECKING p/ não acoplar runtime a SQLModel aqui.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from app.domain.models import ActivityLog, DailyRecord, Employee, Settings


class EmployeeRepository(Protocol):
    def get(self, employee_id: int) -> "Employee | None": ...
    def list_all(self) -> list["Employee"]: ...
    def find_by_name(self, name_lower: str) -> "Employee | None": ...
    def count(self) -> int: ...
    def add(self, emp: "Employee") -> "Employee": ...
    def update(self, emp: "Employee") -> "Employee": ...
    def delete(self, emp: "Employee") -> None: ...


class RecordRepository(Protocol):
    def get(self, record_id: int) -> "DailyRecord | None": ...
    def get_for_day(self, employee_id: int, date: str) -> "DailyRecord | None": ...
    def list_all(self) -> list["DailyRecord"]: ...
    def list_by_employee(self, employee_id: int) -> list["DailyRecord"]: ...
    def list_by_month(self, prefix: str) -> list["DailyRecord"]: ...
    def list_by_status(self, status: str) -> list["DailyRecord"]: ...
    def add(self, rec: "DailyRecord") -> "DailyRecord": ...
    def update(self, rec: "DailyRecord") -> "DailyRecord": ...
    def delete(self, rec: "DailyRecord") -> None: ...


class SettingsRepository(Protocol):
    def get_or_create(self) -> "Settings": ...
    def update(self, settings: "Settings") -> "Settings": ...
    def journey_params(self) -> tuple[int, int]: ...


class AttachmentStorage(Protocol):
    def save(self, record_id: int, filename: str, content: bytes) -> str: ...
    def delete(self, stored_name: str) -> None: ...
    def path(self, stored_name: str) -> "object": ...  # pathlib.Path


class ActivityLogRepository(Protocol):
    def add(self, log: "ActivityLog") -> "ActivityLog": ...
    def list_since(self, since_iso: str) -> list["ActivityLog"]: ...
    def list_for_employee(self, employee_id: int, since_iso: str, until_iso: str) -> list["ActivityLog"]: ...
